# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch("RAILS_DB_HOST") { "db" } %>
  username: <%= ENV.fetch("RAILS_DB_USER_NAME") { "username" } %>
  password: <%= ENV.fetch("RAILS_DB_PASSWORD") { "p@ssw0rd" } %>

development:
  <<: *default
  database: sy_development
test:
  <<: *default
  database: sy__test
production:
  <<: *default
  database: sy__production